<?php

/**
 * @file
 * Contains stc_core.module.
 */

use Drupal\bootstrap\Bootstrap;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stc_core_form_wxt_search_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $wxt_gcweb_search = Bootstrap::getTheme()->getSetting('wxt_gcweb_search');
  if (empty($wxt_gcweb_search)) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    if ($language == 'en') {
      $form['#action'] = 'https://www.statcan.gc.ca/search/results/site-search';
    }
    else {
      $form['#action'] = 'https://www.statcan.gc.ca/recherche/resultats/site-recherche';
    }

    $form['#method'] = 'get';

    $form['keys']['#title'] = t('Search website');
    $form['keys']['#placeholder'] = $form['keys']['#title'];
    $form['keys']['#name'] = 'q';
    $form['keys']['#maxlength'] = 150;
    $form['keys']['#description'] = '';

    $form['fq'] = [
      '#name' => 'fq',
      '#value' => 'stclac:2',
      '#type' => 'hidden',
      '#input' => 'TRUE',
    ];

    $form['submit']['#name'] = 'wb-srch-sub';
    $form['submit']['#value'] = t('Search');
    $form['submit']['#icon_only'] = TRUE;
  }
}

/**
 * Implements hook_metatags_attachments_alter().
 */
function stc_core_metatags_attachments_alter(array &$metatag_attachments) {
  foreach ($metatag_attachments['#attached']['html_head'] as $key => &$tag) {
    switch ($tag[1]) {
      case 'dcterms_subject':
        $tag[0]['#attributes']['title'] = 'gcstc';
        break;
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function stc_core_entity_type_alter(array &$entity_types) {
  $entity_types['user']->addConstraint('UserMailConstraint');
}
