<?php

/**
 * @file
 * Contains stc_core.module.
 */

use Drupal\bootstrap\Bootstrap;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stc_core_form_wxt_search_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $wxt_gcweb_search = Bootstrap::getTheme()->getSetting('wxt_gcweb_search');
  if (empty($wxt_gcweb_search)) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $form['#action'] = '//www120.statcan.gc.ca/stcsr/' . $language . '/ut1/uts';
    $form['#method'] = 'get';

    $form['keys']['#placeholder'] = t('Search website');
    $form['keys']['#name'] = 'q';
    $form['keys']['#maxlength'] = 150;

    $form['fq'] = [
      '#name' => 'fq',
      '#value' => 'stclac:2',
      '#type' => 'hidden',
      '#input' => 'TRUE',
    ];

    $form['submit']['#name'] = 'wb-srch-sub';
    $form['submit']['#value'] = t('Search');
    $form['submit']['#icon_only'] = TRUE;
  }
}
